export type Locale = 'ru' | 'en';
export const dict = {
  ru: {
    heroTitle: "Послания, которые переживут нас",
    heroLead: "Запишите письмо, фото или видео. Мы доставим адресату вовремя — по дате или автоматически, когда вас не станет.",
    ctaStart: "Начать",
    cabinet: "Кабинет",
    recipient: "Получатель",
    message: "Послание",
    text: "Текст",
    audio: "Аудио",
    video: "Видео",
    save: "Сохранить",
    preview: "Предпросмотр",
    downloadCopy: "Скачать копию",
    dropFiles: "Перетащите файл сюда или нажмите, чтобы выбрать",
    recording: "Запись…",
    record: "Записать",
    stop: "Стоп",
    play: "Воспроизвести",
    uploading: "Загрузка…",
    language: "Язык",
    theme: "Тема",
    light: "Светлая",
    dark: "Тёмная",
    system: "Системная",
    viewTitle: "Послание",
  },
  en: {
    heroTitle: "Messages that outlive us",
    heroLead: "Record a letter, photo or video. We’ll deliver it on time — by date or automatically when you’re gone.",
    ctaStart: "Get started",
    cabinet: "Dashboard",
    recipient: "Recipient",
    message: "Message",
    text: "Text",
    audio: "Audio",
    video: "Video",
    save: "Save",
    preview: "Preview",
    downloadCopy: "Download a copy",
    dropFiles: "Drag & drop or click to select",
    recording: "Recording…",
    record: "Record",
    stop: "Stop",
    play: "Play",
    uploading: "Uploading…",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    system: "System",
    viewTitle: "Message",
  }
} as const;
